# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ab3f29ce39dc85b014e30fb3841781f5b1c4906af841f036b9e08e9f2772885ae25945c32b113add35d1f132f2fc9402f588a85cf7edb538fddf9723398ac1

test:
  secret_key_base: 917b74a2f15b9fa32477e37bb6ff0df4262e800f261afe0df932c8d6e81255f76135bae0f26da41799b25cceec5793bb4977bdc1bfc5357404cab04877d84449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
